INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Name', 'Mobile No.');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Leeben', '9688855069');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Akram Khan', '8903938786');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'G.Vijay', '9942277861');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Muhammad jahan', '8056814281');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Sivathanu', '7448663355');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Dinahar Dina', '8110923952');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Thanu siva', '9488108394');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Vishnu', '7550239016');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'AJIN D', '8508302429');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Raja', '8825479945');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Staji S', '9789217310');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Panneer selvam', '9790356186');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Mohammed asbar', '9626072377');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Anish', '9600729901');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Monee M pillai', '9715371757');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Jerry Nissan', '9488858776');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Ajith', '8148534654');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'ajaybasss', '9080539285');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'karthick', '8838766409');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'vigensh', '8778736487');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'S.BENNET', '9965842204');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'John lenold', '9524632669');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', '8vasanth agash', '8056808897');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Arul L. Reetnus', '7666860643');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Iyappan Pillai', '8508786786');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Jerry Nissan', '9488858776');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Pandiyan T', '7356030206');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Bhuvanesh', '7904695660');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'G.MATHANA KUMAR', '9894598180');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Esakimuthu p', '9943758034');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Name', 'Mobile No.');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'T J RICHIE ALLEN VAZ', '8098735098');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Vivek', '9488788070');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'dharshiha', '9442728722');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Staji S', '9789217310');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'PADMA.S', '9944737255');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'satheesh', '9042637455');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'M.S.Monish Kumar', '8122510206');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Mathu', '9940446380');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'C.V.Thanu Thiraviam', '7502812151');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'K.Arun', '7708422538');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'M.Thanumoorthy', '9443607111');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Anand', '9489801999');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'karthickparamesh', '9600890679');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Muthu S s', '7708874017');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Prasanth', '7339074269');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'kajeswaran', '9741298487');
INSERT INTO bloogdonnerslist (dpBloodGroup, dpCountry, dpState, dpDistrict, dpCity, Name, `Mobile No.`) VALUES ('A+', 'INDIA', 'Tamil Nadu', 'Kanyakumari', 'Nagercoil', 'Ajithkumar', '9698679148');
